import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';
import { ptBR, enUS } from 'date-fns/locale';


const getRegionSettings = () => {
    const region = localStorage.getItem('app_region') || 'BR';
    if (region === 'USA') {
        return {
            locale: enUS,
            currency: 'USD',
            currencySymbol: '$',
            decimalSeparator: '.',
            thousandSeparator: ',',
            dateFormat: "MMMM dd, yyyy",
            labels: {
                company: 'COMPANY',
                customer: 'CUSTOMER',
                issueDate: 'Issue Date:',
                item: 'Item',
                description: 'Description',
                qty: 'Qty',
                unitPrice: 'Unit Price',
                subtotal: 'Subtotal',
                total: 'TOTAL',
                page: 'Page',
                of: 'of',
                generatedBy: 'Document generated by METRIX system.',
                quoteValidity: 'This quote is valid for 15 days.'
            }
        };
    }
    return {
        locale: ptBR,
        currency: 'BRL',
        currencySymbol: 'R$',
        decimalSeparator: ',',
        thousandSeparator: '.',
        dateFormat: "dd 'de' MMMM 'de' yyyy",
        labels: {
            company: 'EMPRESA',
            customer: 'CLIENTE',
            issueDate: 'Data de Emissão:',
            item: 'Item',
            description: 'Descrição',
            qty: 'Qtd.',
            unitPrice: 'Preço Unit.',
            subtotal: 'Subtotal',
            total: 'TOTAL',
            page: 'Página',
            of: 'de',
            generatedBy: 'Documento gerado pelo sistema METRIX.',
            quoteValidity: 'Este orçamento é válido por 15 dias.'
        }
    };
};

const formatCurrencyForPdf = (value, settings) => {
    const num = Number(value);
    if (isNaN(num)) {
      return `${settings.currencySymbol} 0${settings.decimalSeparator}00`;
    }
    const [integer, decimal] = num.toFixed(2).split('.');
    const formattedInteger = integer.replace(/\B(?=(\d{3})+(?!\d))/g, settings.thousandSeparator);
    return `${settings.currencySymbol} ${formattedInteger}${settings.decimalSeparator}${decimal || '00'}`;
};

const generatePdf = async (activity, distributorProfile) => {
  if (!activity) {
    console.error("generatePdf called with null or undefined activity.");
    return;
  }

  const doc = new jsPDF();
  const settings = getRegionSettings();
  
  const isSale = activity.status === 'sale_made';
  const documentType = isSale ? (settings.locale === enUS ? 'PROOF OF SALE' : 'COMPROVANTE DE VENDA') : (settings.locale === enUS ? 'QUOTE' : 'ORÇAMENTO');
  const documentTitle = isSale ? (settings.locale === enUS ? 'Proof of Sale' : 'Comprovante de Venda') : (settings.locale === enUS ? 'Quote' : 'Orçamento');
  const referenceNumber = `REF-${String(activity.id || 'N/A').substring(0, 8).toUpperCase()}`;

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let yPos = 0;

  // ==== HEADER ====
  yPos = 30; // Start lower to compensate for removed logo
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(documentTitle, pageWidth / 2, yPos, { align: 'center' });
  yPos += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Nº ${referenceNumber}`, pageWidth / 2, yPos, { align: 'center' });
  yPos += 15;

  // ==== COMPANY AND CUSTOMER INFO ====
  doc.setLineWidth(0.1);
  doc.setDrawColor(220);
  
  const infoBoxWidth = (pageWidth - margin * 3) / 2;
  const infoBoxStartY = yPos;

  // Company Info Box
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text(settings.labels.company, margin + 5, yPos + 6);
  yPos += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(50);
  doc.text(distributorProfile?.name || 'N/A', margin + 5, yPos);
  yPos += 5;
  doc.text(distributorProfile?.email || 'N/A', margin + 5, yPos);
  yPos += 5;
  doc.text(distributorProfile?.address_street ? `${distributorProfile.address_street}, ${distributorProfile.address_number || ''}` : 'N/A', margin + 5, yPos);

  const box1endY = yPos;
  yPos = infoBoxStartY;
  
  // Customer Info Box
  const customerBoxX = margin * 2 + infoBoxWidth;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(0);
  doc.text(settings.labels.customer, customerBoxX + 5, yPos + 6);
  yPos += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(50);
  doc.text(activity.customer_name || 'N/A', customerBoxX + 5, yPos);
  yPos += 5;
  doc.text(activity.customer_phone || 'N/A', customerBoxX + 5, yPos);
  yPos += 5;
  doc.text(activity.customer_address || 'N/A', customerBoxX + 5, yPos);
  
  const infoBoxHeight = Math.max(box1endY, yPos) - infoBoxStartY + 5;
  doc.rect(margin, infoBoxStartY, infoBoxWidth, infoBoxHeight, 'S');
  doc.rect(customerBoxX, infoBoxStartY, infoBoxWidth, infoBoxHeight, 'S');
  
  yPos = infoBoxStartY + infoBoxHeight + 5;
  
  // Date
  doc.setFontSize(10);
  let formattedDate = 'N/A';
  if (activity.visit_date && !isNaN(new Date(activity.visit_date))) {
    formattedDate = format(new Date(activity.visit_date), settings.dateFormat, { locale: settings.locale });
  }
  doc.text(`${settings.labels.issueDate} ${formattedDate}`, margin, yPos);
  yPos += 10;

  // ==== PRODUCTS TABLE ====
  const tableColumn = [settings.labels.item, settings.labels.description, settings.labels.qty, settings.labels.unitPrice, settings.labels.subtotal];
  const tableRows = [];
  const products = activity.opportunity_products || [];

  const totalValue = products.reduce((acc, item) => {
    const quantity = Number(item.quantity_sold) || 0;
    const unitPrice = isSale 
      ? (Number(item.unit_sale_price_at_sale) || 0) 
      : (Number(item.product?.sale_price) || 0);
    return acc + (quantity * unitPrice);
  }, 0);

  products.forEach((item, index) => {
    const quantity = Number(item.quantity_sold) || 0;
    const unitPrice = isSale 
      ? (Number(item.unit_sale_price_at_sale) || 0) 
      : (Number(item.product?.sale_price) || 0);
    const itemSubtotal = quantity * unitPrice;
    
    const row = [
      index + 1,
      item.product?.name || "Produto Desconhecido",
      quantity,
      formatCurrencyForPdf(unitPrice, settings),
      formatCurrencyForPdf(itemSubtotal, settings)
    ];
    tableRows.push(row);
  });

  doc.autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: yPos,
    theme: 'striped',
    headStyles: { fillColor: [34, 41, 47], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: {
        0: { halign: 'center', cellWidth: 15 },
        1: { cellWidth: 'auto' },
        2: { halign: 'center', cellWidth: 15 },
        3: { halign: 'right', cellWidth: 30 },
        4: { halign: 'right', cellWidth: 30 }
    },
  });

  let finalY = doc.lastAutoTable.finalY || yPos + 10;
  yPos = finalY + 8;
  
  // ==== TOTALS SECTION ====
  const totalsX = pageWidth - margin - 70;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text(`${settings.labels.total}:`, totalsX, yPos, { align: 'right' });
  doc.text(formatCurrencyForPdf(totalValue, settings), pageWidth - margin, yPos, { align: 'right' });

  // ==== FOOTER ====
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 15;
  doc.setDrawColor(200);
  doc.line(margin, footerY, pageWidth - margin, footerY);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.setTextColor(150);
  doc.text(settings.labels.generatedBy, margin, footerY + 5);
  doc.text(`${settings.labels.page} 1 ${settings.labels.of} 1`, pageWidth - margin, footerY + 5, { align: 'right' });
  if (!isSale) {
    doc.text(settings.labels.quoteValidity, margin, footerY + 9);
  }

  const safeCustomerName = String(activity.customer_name || 'cliente').replace(/[^a-zA-Z0-9]/g, '_');
  const fileName = `${documentType.toLowerCase().replace(/\s/g, '_')}_${safeCustomerName}_${referenceNumber}.pdf`;
  doc.save(fileName);
};

export default generatePdf;